# Project Euler

# Problem 2: Even Fibonacci numbers
# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

import time


start_time = time.time()
ans_project_2 = int(0)
last_fibonacci = int(0)
next_fibonacci = int(1)
while next_fibonacci < 4000000:
    temp = last_fibonacci
    last_fibonacci = next_fibonacci
    next_fibonacci = temp + last_fibonacci
    if next_fibonacci < 4000000 and next_fibonacci % 2 == 0:
        ans_project_2 += next_fibonacci
print("Problem 2:", ans_project_2)
print("Total time:", time.time() - start_time)
